#!/bin/
language : php

php :
    - 5.6
    - 7.0
services:
  - mysql
  - memcached
before_script :
    - composer install -o
    - cp tests/travis.properties tests/test.properties
    - export PATH="$PATH:$PWD/bin"
    - phing

script:
    - phpunit -c ./ --coverage-text --coverage-clover ../build/logs/clover.xml

after_script:
- php coveralls