runtime: php
env: flexible

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5

runtime_config:
    document_root: public

handlers:
- url: /.*
  script: public/index.php

beta_settings:
    cloud_sql_instances: "eloquent-optics-206213:us-east1:twicbdd"
